name: Update joke

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install

      - name: Generate readme
        run: node index.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Tino Schroeter
          author_email: tino.schroeter@gmail.com
          message: ":robot: Add new Joke =]"
          add: "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
